configuration: Constify more pointers
This continues the patch series constifying various pointers in the
configuration sub-system.

This is done as a separate commit as it involved a _slightly_ more
invasive change in nxt_conf_get_string().

While it takes a value parameter that is never modified, simply making
it const results in

  CC     build/src/nxt_conf.o
src/nxt_conf.c: In function ‘nxt_conf_get_string’:
src/nxt_conf.c:170:20: error: assignment discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
  170 |         str->start = value->u.str.start;
      |                    ^

due to the assignment operator. Making value const will allow for
numerous other constification and seeing as we are not modifying it,
seems worthwhile.

We can get around the warning by casting ->u.{str,string}.start

Reviewed-by: Zhidao HONG <z.hong@f5.com>
Signed-off-by: Andrew Clayton <a.clayton@nginx.com>