ci: Update to actions/upload-artifact@v4 in cifuzz.yml
We need to update to the latest version of actions/upload-artifact in
cifuzz.yml due to the workflow failing because of

  Error: This request has been automatically failed because it uses a
  deprecated version of `actions/upload-artifact: v3`. Learn more:
  https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

Signed-off-by: Andrew Clayton <a.clayton@nginx.com>