Fix build with php85-beta2
References:
- https://wiki.php.net/rfc/remove_disable_classes
- https://github.com/php/php-src/pull/12043

  CC     build/src/nxt_php_sapi-php85.o
cc -c -pipe -fPIC -fvisibility=hidden -fno-strict-overflow -funsigned-char -std=gnu11 -O -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -fno-strict-aliasing -Wstrict-overflow=5 -Wmissing-prototypes -Werror -g  -O2 -pipe  -fstack-protector-strong -fno-strict-aliasing    -I src -I build/include \
-I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -DNXT_ZEND_SIGNAL_STARTUP=1 \
-MMD -MF build/src/nxt_php_sapi-php85.dep -MT build/src/nxt_php_sapi-php85.o \
-o build/src/nxt_php_sapi-php85.o src/nxt_php_sapi.c
src/nxt_php_sapi.c:714:37: error: no member named 'disable_classes' in 'struct _php_core_globals'
  714 |                                 &PG(disable_classes),
      |                                  ~~~^~~~~~~~~~~~~~~~
/usr/local/include/php/main/php_globals.h:31:30: note: expanded from macro 'PG'
   31 | # define PG(v) (core_globals.v)
      |                 ~~~~~~~~~~~~ ^
src/nxt_php_sapi.c:715:33: error: use of undeclared identifier 'zend_disable_class'
  715 |                                 zend_disable_class);
      |                                 ^
2 errors generated.
gmake[1]: *** [build/Makefile:2107: build/src/nxt_php_sapi-php85.o] Error 1