Put function attributes where ISO C2x specifies.
GCC is very generous in where attributes can be placed.  C2x, the
first ISO C standard that will standardize attributes, in order to
be less ambiguous, decided to only allow attributes to be placed
in very specific places.  Function attributes go at the very
beginning of a function prototype (it also allows them to go after
the function identifier and just before the parameter list's
opening parenthesis, but that's a side effect of being compatible
with C++'s syntax, and should probably be never used in C, and
anyway I don't like it for many reasons, including that it breaks
the ability to grep for functions using a regex).

See the following test that helps understand this:

$ cat inline.c
[[gnu::always_inline]] static inline void a(void);
static [[gnu::always_inline]] inline void b(void);
static inline [[gnu::always_inline]] void c(void);
static inline void [[gnu::always_inline]] d(void);
static inline void e [[gnu::always_inline]] (void);
static inline void f(void)[[gnu::always_inline]];
static inline void g(void);

static inline void a(void) { return; }
static inline void b(void) { return; }
static inline void c(void) { return; }
static inline void d(void) { return; }
static inline void e(void) { return; }
static inline void f(void) { return; }
static inline void g(void) { return; }

$ clang -Wall -Wextra -Werror -std=c2x inline.c -c
inline.c:2:8: error: an attribute list cannot appear here
static [[gnu::always_inline]] inline void b(void);
       ^~~~~~~~~~~~~~~~~~~~~~
inline.c:3:15: error: an attribute list cannot appear here
static inline [[gnu::always_inline]] void c(void);
              ^~~~~~~~~~~~~~~~~~~~~~
inline.c:4:22: error: 'always_inline' attribute cannot be applied to types
static inline void [[gnu::always_inline]] d(void);
                     ^
inline.c:6:29: error: attribute 'always_inline' ignored, because it cannot be applied to a type [-Werror,-Wignored-attributes]
static inline void f(void)[[gnu::always_inline]];
                            ^
4 errors generated.

$ cc -Wall -Wextra -Werror -std=c2x inline.c -c
inline.c:2:1: error: ‘always_inline’ attribute does not apply to types [-Werror=attributes]
    2 | static [[gnu::always_inline]] inline void b(void);
      | ^~~~~~
inline.c:2:31: error: expected identifier or ‘(’ before ‘inline’
    2 | static [[gnu::always_inline]] inline void b(void);
      |                               ^~~~~~
inline.c:3:1: error: ‘always_inline’ attribute does not apply to types [-Werror=attributes]
    3 | static inline [[gnu::always_inline]] void c(void);
      | ^~~~~~
inline.c:3:38: error: expected identifier or ‘(’ before ‘void’
    3 | static inline [[gnu::always_inline]] void c(void);
      |                                      ^~~~
inline.c:4:1: error: ‘always_inline’ attribute does not apply to types [-Werror=attributes]
    4 | static inline void [[gnu::always_inline]] d(void);
      | ^~~~~~
inline.c:6:1: error: ‘always_inline’ attribute does not apply to types [-Werror=attributes]
    6 | static inline void f(void)[[gnu::always_inline]];
      | ^~~~~~
cc1: all warnings being treated as errors