Use NULL instead of 0 as null pointer constant
GCC 15 enabled "-Wzero-as-null-pointer-constant" for C, which checks for
places where '0' has been used as a null pointer constant.

This showed a few places in Unit where we were using '0' instead of the
more correct NULL macro. E.g.

  $ make -j4 EXTRA_CFLAGS=-Wzero-as-null-pointer-constant
  ...
  src/nxt_buf.c: In function ‘nxt_buf_mmap_alloc’:
  src/nxt_buf.h:192:21: error: zero as null pointer constant [-Werror=zero-as-null-pointer-constant]
    192 |         (bm)->start = 0;                                                      \
        |                     ^
  src/nxt_buf.c:135:9: note: in expansion of macro ‘nxt_buf_mem_set_size’
    135 |         nxt_buf_mem_set_size(&b->mem, size);
        |         ^~~~~~~~~~~~~~~~~~~~

Signed-off-by: Andrew Clayton <a.clayton@nginx.com>